# -*- coding: utf-8 -*-
"""nilai_eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1bVxR2m1UUkplm7Fytvo5PPHolAL9xr
"""

import numpy as np

A = np.array([[4, 1], [2, 3]])

nilaieigen, vektoreigen = np.linalg.eig(A)

print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as np

A = np.array([[-12, -4], [9, -11]])

nilaieigen, vektoreigen = np.linalg.eig(A)

print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)