# -*- coding: utf-8 -*-
"""suhu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HF50EizkulC40KOPH7vAD2zi0iSUqA7s
"""



import numpy as np
import matplotlib.pyplot as plt

def perubahan_suhu_kopi(Ta,k,t,T0):
    """

    Menghitung perubahan suhu kopi pada k berdasarkan persamaan eksponensial:
    T = Ta + e^(-k*t)* T0

    Parameter:
    Ta  : float, suhu ruangan
    k   : array-like, konstanta laju pendinginan
    t   : array-like, waktu
    T0  : float, suhu awal

    Mengembalikan
    T   : float, suhu akhir
    """
    return Ta + np.exp(-k * t) * T0

# Parameter contoh
Ta  = 28  #suhu ruangan
k   = 0.02
t   = np.linspace(0, 50, 300)
T0  = 44

# Menyelesaikan persamaan
T = perubahan_suhu_kopi(Ta,k,t,T0)

# Plot hasilnya
plt.figure(figsize=(8,6))
plt.plot(t,T, label = f"T = Ta +np.exp(-kt) * T0", color = "red")
plt.title("Perubahan Suhu Kopi pada Suhu Ruangan")
plt.xlabel("Waktu")
plt.ylabel("Suhu")
plt.legend()
plt.grid()
plt.show()