# -*- coding: utf-8 -*-
"""pertumbuhan_rumput_laut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wo2PGhfYllktt7OIY4WwAWG5OW2iZwXW
"""

import numpy as np
import matplotlib.pyplot as plt

def kapasitas_rumput_laut(r, K, P0, time):
  """
  Menghitung kapasitas rumput laut pada
  P = P0 * np.exp(r * (1 - P0/K) * time)

  Parameter:
  r : float, laju pertumbuhan
  K : float
  P0 : float, jumlah awal
  time : array-like, waktu

  Mengembalikan
  P : float, jumlah terhadap waktu
  """
  return P0 * np.exp(r * (1 - P0/K) * time)

#Parameter kasus
r = 0.1                     #Laju pertumbuhan rumput laut
K = 5000                    #Kapasitas wilayah
P0 = 100                    #Populasi awal
time = np.linspace(0, 13)   #waktu

#Penyelesaian
P = kapasitas_rumput_laut(r, K, P0, time)

#Plot
plt.figure(figsize=(8, 6))
plt.plot(time, P, label = f"P = P0 * np.exp(r * (1 - P0/K) * time)", color = "green")
plt.xlabel("Waktu (Bulan)")
plt.ylabel("Jumlah Populasi")
plt.title("Pertumbuhan Rumput Laut")
plt.legend()
plt.grid()
plt.show()