# -*- coding: utf-8 -*-
"""Tugas_3_SIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F7us8ggR0O5fPd1JOBk3F4OtKcf-YyE6
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter model
beta = 0.2        # laju infeksi
gamma= 1/10       # laju pemulihan (1/gamma = 10 hari)
N = 1000          # total populasi
alpha = 0.02      # laju  kelahiran
sigma = 0.01      # laju kematian

# Kondisi awal
S0 = N-1  # SEMUA INDIVIDU RENTAN KECUALI 1 YANG TERINFEKSI
I0 = 1    # INDIVIDU TERINFEKSI PADA AWALNYA
R0 = 0    # TIDAK ADA YAMG SEMBUH PADA AWALNYA

# WAKTU SIMULASI (DALAM HARI)
t = np.linspace(0, 300, 300) # simulasi selama 300 hari

# model SIR
def sir_model(y, t, N, beta, gamma, alpha, sigma):
  S, I, R = y
  dsdt = alpha * N - (beta * S * I / N) - sigma * S
  dIdt = beta * S * I / N - gamma * I - sigma * I
  dRdt = gamma * I - sigma * R
  return [dsdt, dIdt, dRdt]

# Menyelesaikan sistem persamaan diferensial
y0 = [S0, I0, R0]
solution = odeint(sir_model, y0, t, args=(N, beta, gamma, alpha, sigma))
S, I, R = solution.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color ='blue')
plt.plot(t, I, label='Infected', color = 'red')
plt.plot(t, R, label='Recovered', color = 'green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SIR', color = 'pink')
plt.legend()
plt.grid()
plt.show()